// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrmpplhkntvnmeeespzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ybXBwbGhrbnR2bm1lZWVzcHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1ODQ5MDAsImV4cCI6MjA1MTE2MDkwMH0.3GHD_IGN4I-y-KhvfXDGK1uVBrdScMeEaH9cxYFRhhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);